CUDA_DIR := /usr/local/cuda

CUDA_ARCH := \
    -gencode arch=compute_86,code=sm_86 \
    -gencode arch=compute_89,code=sm_89 \
    -gencode arch=compute_89,code=compute_89

USE_CUDNN := 0

BLAS := open

PYTHON_INCLUDE := /usr/include/python3.10 \
                  /usr/lib/python3/dist-packages/numpy/core/include

PYTHON_LIB := /usr/lib

OPENCV_VERSION := 4

INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/opencv4 /usr/include/hdf5/serial
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/hdf5/serial

USE_NCCL := 0

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

TEST_GPUID := 0

USE_HDF5 := 1

Q ?= @

